##########################################################
# +————————————————————————————————————————————————————+ #
# |—————————  COMMANDEXECUTOR CONFIGURATION  ——————————| #
# |——————————————————       v1       ——————————————————| #
# +————————————————————————————————————————————————————+ #
# |         For any bug/questions/suggestions:         | #
# |               visit the main thread.               | #
# +————————————————————————————————————————————————————+ #
##########################################################
# Permissions list:
#  - commandexecutor.access : give access to the command


# +————————————————————————————————————+ #
# |————        Configuration       ————| #
# +————————————————————————————————————+ #

# List of commands executed by console when a player enter /ce <command> (or his aliases); without backslash '/'
# Every commands can be renammed by aliases
# %player% = player name
commands: 
  command1:
  - 'kill %player%'
  - 'say I just killed %player%!'
  command2:
  - 'say %player% said hello!'

no-perm: '&cYou don''t have permission.'
unknown-command: '&cUnknown command. Type "/help" for help.'
sendConsoleMessage: true