name: CommandExecutor
main: fr.andross.commandexecutor.CommandExecutor
version: '1.4'
api-version: '1.13'
author: _Andross
description: Add easily aliases for commands
commands:
  commandexecutor:
    commandexecutor: Main command for the plugin. Display help.
    aliases: [ce]
premissions:
  commandexecutor.access:
    default: true
    description: give access to the command
  commandexecutor.reload:
    description: give access to the reload command
