name: CommandExecutor
main: fr.commandexecutor.CommandExecutor
version: 1.3
author: _Andross
description: Add easily aliases for commands
commands:
  commandexecutor:
    commandexecutor: Main command for the plugin. Display help.
    usage: /<command>
    aliases: [ce]
premissions:
  commandexecutor.access:
    default: true
    description: give access to the command
  commandexecutor.reload:
    description: give access to the reload command
